spring:
  application:
    name: resilience4j-example

resilience4j:
  circuitbreaker:
    instances:
      myService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
